/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isDeal' : IDL.Bool,
  'specs' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'imageId' : ExternalBlob,
  'price' : IDL.Nat,
  'isAccessory' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const ShoppingCart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const WishList = IDL.Record({ 'productIds' : IDL.Vec(IDL.Nat) });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func([Product], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAccessories' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [ShoppingCart], ['query']),
  'getDealProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([IDL.Principal], [WishList], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isDeal' : IDL.Bool,
    'specs' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'imageId' : ExternalBlob,
    'price' : IDL.Nat,
    'isAccessory' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const ShoppingCart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const WishList = IDL.Record({ 'productIds' : IDL.Vec(IDL.Nat) });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func([Product], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAccessories' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [ShoppingCart], ['query']),
    'getDealProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([IDL.Principal], [WishList], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };